-- Service Pages Comprehensive Translations - Part 2 (Technical, Mental, Analysis, Action Reports)

INSERT INTO translations (page_name, text_key, english, spanish, portuguese, french, german, italian, polish, czech, russian, turkish, croatian, norwegian) VALUES
-- TECHNICAL PAGE
('services_technical', 'category', 'TECHNICAL', 'TÉCNICO', 'TÉCNICO', 'TECHNIQUE', 'TECHNISCH', 'TECNICO', 'TECHNIKA', 'TECHNIKA', 'ТЕХНИКА', 'TEKNİK', 'TEHNIKA', 'TEKNISK'),
('services_technical', 'title', 'CONTROL THE BALL CONTROL THE GAME', 'CONTROLA EL BALÓN CONTROLA EL JUEGO', 'CONTROLE A BOLA CONTROLE O JOGO', 'CONTRÔLEZ LE BALLON CONTRÔLEZ LE JEU', 'KONTROLLIERE DEN BALL KONTROLLIERE DAS SPIEL', 'CONTROLLA LA PALLA CONTROLLA IL GIOCO', 'KONTROLUJ PIŁKĘ KONTROLUJ GRĘ', 'OVLÁDNI MÍČ OVLÁDNI HRU', 'КОНТРОЛИРУЙ МЯЧ КОНТРОЛИРУЙ ИГРУ', 'TOPU KONTROL ET OYUNU KONTROL ET', 'KONTROLIRAJ LOPTU KONTROLIRAJ IGRU', 'KONTROLLER BALLEN KONTROLLER SPILLET'),
('services_technical', 'receiving', 'RECEIVING', 'RECEPCIÓN', 'RECEPÇÃO', 'RÉCEPTION', 'ANNAHME', 'RICEZIONE', 'PRZYJĘCIE', 'PŘÍJEM', 'ПРИЁМ', 'ALMA', 'PRIMANJE', 'MOTTAK'),
('services_technical', 'passing', 'PASSING', 'PASE', 'PASSE', 'PASSE', 'PASSEN', 'PASSAGGIO', 'PODANIE', 'PŘIHRÁVKA', 'ПЕРЕДАЧА', 'PAS', 'DODAVANJE', 'PASNING'),
('services_technical', 'dribbling', 'DRIBBLING', 'REGATE', 'DRIBLE', 'DRIBBLE', 'DRIBBLING', 'DRIBBLING', 'DRYBLING', 'DRIBLING', 'ДРИБЛИНГ', 'DRİBLİNG', 'DRIBLING', 'DRIBLING'),
('services_technical', 'finishing', 'FINISHING', 'FINALIZACIÓN', 'FINALIZAÇÃO', 'FINITION', 'ABSCHLUSS', 'FINALIZZAZIONE', 'WYKOŃCZENIE', 'ZAKONČENÍ', 'ЗАВЕРШЕНИЕ', 'BİTİRİCİLİK', 'ZAVRŠNICA', 'AVSLUTNING'),
('services_technical', 'more_than_cones', 'MORE THAN CONES', 'MÁS QUE CONOS', 'MAIS QUE CONES', 'PLUS QUE DES CÔNES', 'MEHR ALS HÜTCHEN', 'PIÙ DI CONI', 'WIĘCEJ NIŻ PACHOŁKI', 'VÍCE NEŽ KUŽELY', 'БОЛЬШЕ, ЧЕМ КОНУСЫ', 'KONLARDAN FAZLASI', 'VIŠE OD ČUNJEVA', 'MER ENN KJEGLER'),

-- MENTAL PAGE
('services_mental', 'category', 'PSYCHOLOGICAL PERFORMANCE', 'RENDIMIENTO PSICOLÓGICO', 'DESEMPENHO PSICOLÓGICO', 'PERFORMANCE PSYCHOLOGIQUE', 'PSYCHOLOGISCHE LEISTUNG', 'PRESTAZIONE PSICOLOGICA', 'WYDAJNOŚĆ PSYCHOLOGICZNA', 'PSYCHOLOGICKÝ VÝKON', 'ПСИХОЛОГИЧЕСКАЯ ЭФФЕКТИВНОСТЬ', 'PSİKOLOJİK PERFORMANS', 'PSIHOLOŠKA IZVEDBA', 'PSYKOLOGISK YTELSE'),
('services_mental', 'title', 'SKILL + WILL = SUCCESS', 'HABILIDAD + VOLUNTAD = ÉXITO', 'HABILIDADE + VONTADE = SUCESSO', 'COMPÉTENCE + VOLONTÉ = SUCCÈS', 'KÖNNEN + WOLLEN = ERFOLG', 'ABILITÀ + VOLONTÀ = SUCCESSO', 'UMIEJĘTNOŚĆ + WOLA = SUKCES', 'DOVEDNOST + VŮLE = ÚSPĚCH', 'НАВЫК + ВОЛЯ = УСПЕХ', 'YETENEK + İRADE = BAŞARI', 'VJEŠTINA + VOLJA = USPJEH', 'FERDIGHET + VILJE = SUKSESS'),
('services_mental', 'subtitle', 'Football is not solely about skill. The fine margins are decided by will.', 'El fútbol no es solo habilidad. Los márgenes finos los decide la voluntad.', 'O futebol não é apenas sobre habilidade. As margens finas são decididas pela vontade.', 'Le football ne concerne pas uniquement les compétences. Les marges fines sont décidées par la volonté.', 'Fußball dreht sich nicht nur um Können. Die feinen Margen werden durch Willen entschieden.', 'Il calcio non riguarda solo l''abilità. I margini sottili sono decisi dalla volontà.', 'Piłka nożna to nie tylko umiejętności. O drobnych różnicach decyduje wola.', 'Fotbal není jen o dovednostech. Jemné nuance rozhoduje vůle.', 'Футбол - это не только навыки. Тонкие грани решает воля.', 'Futbol sadece yetenek değildir. İnce farklar iradeyle belirlenir.', 'Nogomet nije samo vještina. Fine margine odlučuje volja.', 'Fotball handler ikke bare om ferdighet. De fine marginene avgjøres av vilje.'),
('services_mental', 'consistency', 'CONSISTENCY', 'CONSISTENCIA', 'CONSISTÊNCIA', 'COHÉRENCE', 'BESTÄNDIGKEIT', 'COSTANZA', 'KONSEKWENCJA', 'KONZISTENCE', 'ПОСЛЕДОВАТЕЛЬНОСТЬ', 'TUTARLILIK', 'DOSLJEDNOST', 'KONSISTENS'),
('services_mental', 'focus', 'FOCUS', 'ENFOQUE', 'FOCO', 'CONCENTRATION', 'FOKUS', 'CONCENTRAZIONE', 'SKUPIENIE', 'SOUSTŘEDĚNÍ', 'ФОКУС', 'ODAKLANMA', 'FOKUS', 'FOKUS'),
('services_mental', 'resilience', 'RESILIENCE', 'RESILIENCIA', 'RESILIÊNCIA', 'RÉSILIENCE', 'RESILIENZ', 'RESILIENZA', 'ODPORNOŚĆ', 'ODOLNOST', 'УСТОЙЧИВОСТЬ', 'DAYANIKLILIK', 'OTPORNOST', 'MOTSTANDSDYKTIGHET'),
('services_mental', 'confidence', 'CONFIDENCE', 'CONFIANZA', 'CONFIANÇA', 'CONFIANCE', 'SELBSTVERTRAUEN', 'FIDUCIA', 'PEWNOŚĆ SIEBIE', 'SEBEVĚDOMÍ', 'УВЕРЕННОСТЬ', 'GÜVEN', 'SAMOPOUZDANJE', 'SELVTILLIT'),
('services_mental', 'podcast', 'PODCAST', 'PODCAST', 'PODCAST', 'PODCAST', 'PODCAST', 'PODCAST', 'PODCAST', 'PODCAST', 'ПОДКАСТ', 'PODCAST', 'PODCAST', 'PODCAST'),
('services_mental', 'performance', 'Performance', 'Rendimiento', 'Desempenho', 'Performance', 'Leistung', 'Prestazione', 'Wydajność', 'Výkon', 'Производительность', 'Performans', 'Izvedba', 'Ytelse'),
('services_mental', 'development', 'Development', 'Desarrollo', 'Desenvolvimento', 'Développement', 'Entwicklung', 'Sviluppo', 'Rozwój', 'Rozvoj', 'Развитие', 'Gelişim', 'Razvoj', 'Utvikling'),
('services_mental', 'mental_will_training', 'Mental Will Training', 'Entrenamiento de Voluntad Mental', 'Treino de Vontade Mental', 'Entraînement de la Volonté Mentale', 'Mentales Willenstraining', 'Allenamento della Volontà Mentale', 'Trening Woli Mentalnej', 'Trénink Mentální Vůle', 'Тренировка Ментальной Воли', 'Zihinsel İrade Antrenmanı', 'Trening Mentalne Volje', 'Mental Viljetrening'),
('services_mental', 'mental_skill_training', 'Mental Skill Training', 'Entrenamiento de Habilidades Mentales', 'Treino de Habilidades Mentais', 'Entraînement des Compétences Mentales', 'Mentales Fertigkeitstraining', 'Allenamento delle Abilità Mentali', 'Trening Umiejętności Mentalnych', 'Trénink Mentálních Dovedností', 'Тренировка Ментальных Навыков', 'Zihinsel Beceri Antrenmanı', 'Trening Mentalnih Vještina', 'Mental Ferdighetstrening'),

-- ANALYSIS PAGE
('services_analysis', 'category', 'ANALYSIS', 'ANÁLISIS', 'ANÁLISE', 'ANALYSE', 'ANALYSE', 'ANALISI', 'ANALIZA', 'ANALÝZA', 'АНАЛИЗ', 'ANALİZ', 'ANALIZA', 'ANALYSE'),
('services_analysis', 'pre_match_title', 'PRE-MATCH OPPOSITION ANALYSIS', 'ANÁLISIS PRE-PARTIDO DEL RIVAL', 'ANÁLISE PRÉ-JOGO DO ADVERSÁRIO', 'ANALYSE DE L''ADVERSAIRE AVANT-MATCH', 'GEGNERANALYSE VOR DEM SPIEL', 'ANALISI AVVERSARIO PRE-PARTITA', 'ANALIZA RYWALA PRZED MECZEM', 'PŘEDZÁPASOVÁ ANALÝZA SOUPEŘE', 'ПРЕДМАТЧЕВЫЙ АНАЛИЗ СОПЕРНИКА', 'MAÇ ÖNCESİ RAKİP ANALİZİ', 'PRETPRIJUGOVORSKA ANALIZA PROTIVNIKA', 'ANALYSE AV MOTSTANDER FØR KAMP'),
('services_analysis', 'post_match_title', 'POST-MATCH ANALYSIS', 'ANÁLISIS POST-PARTIDO', 'ANÁLISE PÓS-JOGO', 'ANALYSE APRÈS-MATCH', 'NACHSPIELANALYSE', 'ANALISI POST-PARTITA', 'ANALIZA PO MECZU', 'POZÁPASOVÁ ANALÝZA', 'ПОСЛЕМАТЧЕВЫЙ АНАЛИЗ', 'MAÇ SONRASI ANALİZ', 'ANALIZA NAKON UTAKMICE', 'ANALYSE ETTER KAMP'),
('services_analysis', 'positional_guide', 'POSITIONAL GUIDE', 'GUÍA POSICIONAL', 'GUIA POSICIONAL', 'GUIDE POSITIONNEL', 'POSITIONSANLEITUNG', 'GUIDA POSIZIONALE', 'PRZEWODNIK POZYCYJNY', 'POZIČNÍ PRŮVODCE', 'ПОЗИЦИОННЫЙ ГАЙД', 'POZİSYON REHBERİ', 'POZICIJSKI VODIČ', 'POSISJONSGUIDE'),
('services_analysis', 'player_efficiency', 'PLAYER EFFICIENCY REPORT', 'INFORME DE EFICIENCIA DEL JUGADOR', 'RELATÓRIO DE EFICIÊNCIA DO JOGADOR', 'RAPPORT D''EFFICACITÉ DU JOUEUR', 'SPIELER-EFFIZIENZ-BERICHT', 'RAPPORTO EFFICIENZA GIOCATORE', 'RAPORT EFEKTYWNOŚCI GRACZA', 'ZPRÁVA O EFEKTIVITĚ HRÁČE', 'ОТЧЕТ ОБ ЭФФЕКТИВНОСТИ ИГРОКА', 'OYUNCU VERİMLİLİK RAPORU', 'IZVJEŠTAJ O UČINKOVITOSTI IGRAČA', 'SPILLEREFFEKTIVITETSRAPPORT'),
('services_analysis', 'request_quote', 'REQUEST A QUOTE', 'SOLICITAR PRESUPUESTO', 'SOLICITAR ORÇAMENTO', 'DEMANDER UN DEVIS', 'ANGEBOT ANFORDERN', 'RICHIEDI UN PREVENTIVO', 'POPROŚ O WYCENĘ', 'POŽÁDAT O NABÍDKU', 'ЗАПРОСИТЬ ЦЕНУ', 'TEKLİF İSTE', 'ZATRAŽITE PONUDU', 'BE OM TILBUD'),

-- ACTION REPORTS PAGE
('services_action_reports', 'category', 'TACTICAL', 'TÁCTICO', 'TÁTICO', 'TACTIQUE', 'TAKTISCH', 'TATTICO', 'TAKTYKA', 'TAKTIKA', 'ТАКТИКА', 'TAKTİK', 'TAKTIKA', 'TAKTIKK'),
('services_action_reports', 'title', 'ACTION REPORTS', 'INFORMES DE ACCIONES', 'RELATÓRIOS DE AÇÕES', 'RAPPORTS D''ACTIONS', 'AKTIONSBERICHTE', 'RAPPORTI AZIONI', 'RAPORTY AKCJI', 'AKČNÍ ZPRÁVY', 'ОТЧЕТЫ О ДЕЙСТВИЯХ', 'AKSİYON RAPORLARI', 'IZVJEŠTAJI O AKCIJAMA', 'HANDLINGSRAPPORTER'),
('services_action_reports', 'what_are', 'WHAT ARE ACTION REPORTS?', '¿QUÉ SON LOS INFORMES DE ACCIONES?', 'O QUE SÃO RELATÓRIOS DE AÇÕES?', 'QU''EST-CE QUE LES RAPPORTS D''ACTIONS?', 'WAS SIND AKTIONSBERICHTE?', 'COSA SONO I RAPPORTI AZIONI?', 'CZYM SĄ RAPORTY AKCJI?', 'CO JSOU AKČNÍ ZPRÁVY?', 'ЧТО ТАКОЕ ОТЧЕТЫ О ДЕЙСТВИЯХ?', 'AKSİYON RAPORLARI NEDİR?', 'ŠTO SU IZVJEŠTAJI O AKCIJAMA?', 'HVA ER HANDLINGSRAPPORTER?'),
('services_action_reports', 'how_it_works', 'HOW IT WORKS', 'CÓMO FUNCIONA', 'COMO FUNCIONA', 'COMMENT ÇA FONCTIONNE', 'WIE ES FUNKTIONIERT', 'COME FUNZIONA', 'JAK TO DZIAŁA', 'JAK TO FUNGUJE', 'КАК ЭТО РАБОТАЕТ', 'NASIL ÇALIŞIR', 'KAKO FUNKCIONIRA', 'HVORDAN DET FUNGERER'),
('services_action_reports', 'whats_included', 'WHAT''S INCLUDED', 'QUÉ INCLUYE', 'O QUE ESTÁ INCLUÍDO', 'CE QUI EST INCLUS', 'WAS ENTHALTEN IST', 'COSA È INCLUSO', 'CO JEST ZAWARTE', 'CO JE ZAHRNUTO', 'ЧТО ВКЛЮЧЕНО', 'NELER DAHİL', 'ŠTO JE UKLJUČENO', 'HVA SOM ER INKLUDERT'),
('services_action_reports', 'pricing', 'PRICING', 'PRECIOS', 'PREÇOS', 'TARIFS', 'PREISE', 'PREZZI', 'CENNIK', 'CENÍK', 'ЦЕНЫ', 'FİYATLANDIRMA', 'CIJENE', 'PRISER'),
('services_action_reports', 'video_submission', 'VIDEO SUBMISSION', 'ENVÍO DE VIDEO', 'ENVIO DE VÍDEO', 'SOUMISSION VIDÉO', 'VIDEO-EINREICHUNG', 'INVIO VIDEO', 'PRZESŁANIE WIDEO', 'ODESLÁNÍ VIDEA', 'ОТПРАВКА ВИДЕО', 'VİDEO GÖNDERİMİ', 'SLANJE VIDEA', 'VIDEOINNSENDING'),
('services_action_reports', 'action_logging', 'ACTION LOGGING', 'REGISTRO DE ACCIONES', 'REGISTRO DE AÇÕES', 'JOURNALISATION DES ACTIONS', 'AKTIONSPROTOKOLLIERUNG', 'REGISTRAZIONE AZIONI', 'REJESTROWANIE AKCJI', 'ZAZNAMENÁVÁNÍ AKCÍ', 'ЛОГИРОВАНИЕ ДЕЙСТВИЙ', 'AKSİYON KAYDI', 'EVIDENTIRANJE AKCIJA', 'HANDLINGSLOGGING'),
('services_action_reports', 'deep_analysis', 'DEEP ANALYSIS', 'ANÁLISIS PROFUNDO', 'ANÁLISE PROFUNDA', 'ANALYSE APPROFONDIE', 'TIEFENANALYSE', 'ANALISI APPROFONDITA', 'GŁĘBOKA ANALIZA', 'HLOUBKOVÁ ANALÝZA', 'ГЛУБОКИЙ АНАЛИЗ', 'DERİN ANALİZ', 'DUBOKA ANALIZA', 'DYBDEANALYSE'),
('services_action_reports', 'report_delivery', 'REPORT DELIVERY', 'ENTREGA DEL INFORME', 'ENTREGA DO RELATÓRIO', 'LIVRAISON DU RAPPORT', 'BERICHTZUSTELLUNG', 'CONSEGNA RAPPORTO', 'DOSTARCZENIE RAPORTU', 'DORUČENÍ ZPRÁVY', 'ДОСТАВКА ОТЧЕТА', 'RAPOR TESLİMİ', 'DOSTAVA IZVJEŠTAJA', 'RAPPORTLEVERING'),
('services_action_reports', 'action_breakdown', 'ACTION BREAKDOWN', 'DESGLOSE DE ACCIONES', 'DETALHAMENTO DE AÇÕES', 'DÉCOMPOSITION DES ACTIONS', 'AKTIONSAUFSCHLÜSSELUNG', 'ANALISI DELLE AZIONI', 'PODZIAŁ AKCJI', 'ROZBOR AKCÍ', 'РАЗБОР ДЕЙСТВИЙ', 'AKSİYON DÖKÜMÜ', 'RAŠČLAMBA AKCIJA', 'HANDLINGSOVERSIKT'),
('services_action_reports', 'tactical_scoring', 'TACTICAL SCORING', 'PUNTUACIÓN TÁCTICA', 'PONTUAÇÃO TÁTICA', 'NOTATION TACTIQUE', 'TAKTISCHE BEWERTUNG', 'PUNTEGGIO TATTICO', 'OCENA TAKTYCZNA', 'TAKTICKÉ HODNOCENÍ', 'ТАКТИЧЕСКАЯ ОЦЕНКА', 'TAKTİK PUANLAMA', 'TAKTIČKO BODOVANJE', 'TAKTISK POENGSUM'),
('services_action_reports', 'video_clips', 'VIDEO CLIPS', 'CLIPS DE VIDEO', 'CLIPES DE VÍDEO', 'CLIPS VIDÉO', 'VIDEOCLIPS', 'CLIP VIDEO', 'KLIPY WIDEO', 'VIDEOKLIPY', 'ВИДЕОКЛИПЫ', 'VİDEO KLİPLER', 'VIDEO ISJEČCI', 'VIDEOKLIPP'),
('services_action_reports', 'insights_recommendations', 'INSIGHTS & RECOMMENDATIONS', 'PERSPECTIVAS Y RECOMENDACIONES', 'INSIGHTS E RECOMENDAÇÕES', 'INSIGHTS ET RECOMMANDATIONS', 'ERKENNTNISSE UND EMPFEHLUNGEN', 'APPROFONDIMENTI E RACCOMANDAZIONI', 'WNIOSKI I REKOMENDACJE', 'POZNATKY A DOPORUČENÍ', 'ВЫВОДЫ И РЕКОМЕНДАЦИИ', 'İÇGÖRÜLER VE ÖNERİLER', 'UVIDI I PREPORUKE', 'INNSIKT OG ANBEFALINGER'),
('services_action_reports', 'ready_to_understand', 'READY TO UNDERSTAND YOUR GAME?', '¿LISTO PARA ENTENDER TU JUEGO?', 'PRONTO PARA ENTENDER SEU JOGO?', 'PRÊT À COMPRENDRE VOTRE JEU?', 'BEREIT, IHR SPIEL ZU VERSTEHEN?', 'PRONTO A CAPIRE IL TUO GIOCO?', 'GOTOWY ZROZUMIEĆ SWOJĄ GRĘ?', 'PŘIPRAVEN POCHOPIT SVOU HRU?', 'ГОТОВЫ ПОНЯТЬ СВОЮ ИГРУ?', 'OYUNUNUZU ANLAMAYA HAZIR MISINIZ?', 'SPREMNI RAZUMJETI SVOJU IGRU?', 'KLAR TIL Å FORSTÅ SPILLET DITT?'),
('services_action_reports', 'book_report', 'Book Your Report', 'Reserva Tu Informe', 'Reserve Seu Relatório', 'Réservez Votre Rapport', 'Buchen Sie Ihren Bericht', 'Prenota Il Tuo Rapporto', 'Zamów Swój Raport', 'Zarezervujte Svou Zprávu', 'Забронируйте Ваш Отчет', 'Raporunuzu Ayırtın', 'Rezervirajte Vaš Izvještaj', 'Bestill Rapporten Din')
ON CONFLICT DO NOTHING;