-- Service Pages Comprehensive Translations - Part 1

INSERT INTO translations (page_name, text_key, english, spanish, portuguese, french, german, italian, polish, czech, russian, turkish, croatian, norwegian) VALUES
-- TACTICAL PAGE
('services_tactical', 'category', 'TACTICAL', 'TÁCTICO', 'TÁTICO', 'TACTIQUE', 'TAKTISCH', 'TATTICO', 'TAKTYKA', 'TAKTIKA', 'ТАКТИКА', 'TAKTİK', 'TAKTIKA', 'TAKTIKK'),
('services_tactical', 'title', 'SEE THE GAME BEFORE IT HAPPENS', 'VE EL JUEGO ANTES DE QUE SUCEDA', 'VEJA O JOGO ANTES DE ACONTECER', 'VOYEZ LE JEU AVANT QU''IL SE PRODUISE', 'SEHEN SIE DAS SPIEL BEVOR ES PASSIERT', 'VEDI IL GIOCO PRIMA CHE ACCADA', 'ZOBACZ GRĘ ZANIM SIĘ WYDARZY', 'VIĎTE HRU DŘÍVE NEŽ SE STANE', 'ВИДИТЕ ИГРУ ДО ТОГО, КАК ОНА ПРОИЗОЙДЕТ', 'MAÇI OLMADAN ÖNCE GÖRÜN', 'VIDITE IGRU PRIJE NEGO SE DOGODI', 'SE KAMPEN FØR DEN SKJER'),
('services_tactical', 'in_detail', 'IN DETAIL', 'EN DETALLE', 'EM DETALHE', 'EN DÉTAIL', 'IM DETAIL', 'NEI DETTAGLI', 'SZCZEGÓŁOWO', 'PODROBNĚ', 'ПОДРОБНО', 'DETAYLI', 'DETALJNO', 'I DETALJ'),
('services_tactical', 'key_areas', 'KEY AREAS', 'ÁREAS CLAVE', 'ÁREAS CHAVE', 'DOMAINES CLÉS', 'KERNBEREICHE', 'AREE CHIAVE', 'KLUCZOWE OBSZARY', 'KLÍČOVÉ OBLASTI', 'КЛЮЧЕВЫЕ ОБЛАСТИ', 'TEMEL ALANLAR', 'KLJUČNA PODRUČJA', 'NØKKELOMRÅDER'),
('services_tactical', 'tactical_services', 'TACTICAL SERVICES', 'SERVICIOS TÁCTICOS', 'SERVIÇOS TÁTICOS', 'SERVICES TACTIQUES', 'TAKTISCHE DIENSTE', 'SERVIZI TATTICI', 'USŁUGI TAKTYCZNE', 'TAKTICKÉ SLUŽBY', 'ТАКТИЧЕСКИЕ УСЛУГИ', 'TAKTİK HİZMETLER', 'TAKTIČKE USLUGE', 'TAKTISKE TJENESTER'),

-- SPS PAGE
('services_sps', 'category', 'STRENGTH, POWER & SPEED', 'FUERZA, POTENCIA Y VELOCIDAD', 'FORÇA, POTÊNCIA E VELOCIDADE', 'FORCE, PUISSANCE ET VITESSE', 'KRAFT, POWER UND GESCHWINDIGKEIT', 'FORZA, POTENZA E VELOCITÀ', 'SIŁA, MOC I SZYBKOŚĆ', 'SÍLA, VÝBUŠNOST A RYCHLOST', 'СИЛА, МОЩНОСТЬ И СКОРОСТЬ', 'GÜÇ, PATLAMA VE HIZ', 'SNAGA, MOĆ I BRZINA', 'STYRKE, KRAFT OG HASTIGHET'),
('services_sps', 'title', 'RUN LIKE A SPORTS CAR NOT A HATCHBACK', 'CORRE COMO UN DEPORTIVO, NO COMO UN UTILITARIO', 'CORRA COMO UM CARRO ESPORTIVO, NÃO COMO UM HATCH', 'COUREZ COMME UNE VOITURE DE SPORT, PAS COMME UNE CITADINE', 'LAUFEN WIE EIN SPORTWAGEN, NICHT WIE EIN KLEINWAGEN', 'CORRI COME UN''AUTO SPORTIVA, NON COME UN''UTILITARIA', 'BIEGAJ JAK SAMOCHÓD SPORTOWY, NIE JAK KOMPAKT', 'BĚŽTE JAKO SPORTOVNÍ VŮZ, NE JAKO MALÉ AUTO', 'БЕГИТЕ КАК СПОРТКАР, А НЕ КАК ХЭТЧБЕК', 'SPOR ARABA GİBİ KOŞ, EKONOMİK ARABA GİBİ DEĞİL', 'TRČI KAO SPORTSKI AUTO, NE KAO GRADSKI', 'LØPE SOM EN SPORTSBIL, IKKE SOM EN SMÅBIL'),
('services_sps', 'training', 'TRAINING', 'ENTRENAMIENTO', 'TREINO', 'ENTRAÎNEMENT', 'TRAINING', 'ALLENAMENTO', 'TRENING', 'TRÉNINK', 'ТРЕНИРОВКИ', 'ANTRENMAN', 'TRENING', 'TRENING'),
('services_sps', 'programming', 'PROGRAMMING', 'PROGRAMACIÓN', 'PROGRAMAÇÃO', 'PROGRAMMATION', 'PROGRAMMIERUNG', 'PROGRAMMAZIONE', 'PROGRAMOWANIE', 'PROGRAMOVÁNÍ', 'ПРОГРАММИРОВАНИЕ', 'PROGRAMLAMA', 'PROGRAMIRANJE', 'PROGRAMMERING'),
('services_sps', 'options', 'OPTIONS', 'OPCIONES', 'OPÇÕES', 'OPTIONS', 'OPTIONEN', 'OPZIONI', 'OPCJE', 'MOŽNOSTI', 'ОПЦИИ', 'SEÇENEKLER', 'OPCIJE', 'ALTERNATIVER'),

-- CONDITIONING PAGE
('services_conditioning', 'category', 'CONDITIONING', 'ACONDICIONAMIENTO', 'CONDICIONAMENTO', 'CONDITIONNEMENT', 'KONDITIONIERUNG', 'CONDIZIONAMENTO', 'KONDYCJA', 'KONDICE', 'КОНДИЦИОНИРОВАНИЕ', 'KONDİSYON', 'KONDICIJA', 'KONDISJONERING'),
('services_conditioning', 'title', 'THE CAPACITY TO COVER EVERY BLADE', 'LA CAPACIDAD DE CUBRIR CADA BRIZNA', 'A CAPACIDADE DE COBRIR CADA FOLHA', 'LA CAPACITÉ DE COUVRIR CHAQUE BRIN', 'DIE FÄHIGKEIT, JEDEN GRASHALM ZU BEDECKEN', 'LA CAPACITÀ DI COPRIRE OGNI FILO', 'ZDOLNOŚĆ POKRYCIA KAŻDEGO ŹDŹBŁA', 'SCHOPNOST POKRÝT KAŽDÉ STÉBLO', 'СПОСОБНОСТЬ ПОКРЫТЬ КАЖДУЮ ТРАВИНКУ', 'HER ÇİMENİ KAPAMA KAPASİTESİ', 'SPOSOBNOST POKRITI SVAKU TRAVKU', 'KAPASITETEN TIL Å DEKKE HVERT STRÅ'),
('services_conditioning', 'sharpen_blade', 'SHARPEN YOUR BLADE', 'AFILA TU ESPADA', 'AFIE SUA LÂMINA', 'AFFÛTEZ VOTRE LAME', 'SCHÄRFEN SIE IHRE KLINGE', 'AFFILA LA TUA LAMA', 'NAOSTRZ SWOJE OSTRZE', 'NAOSTŘETE SVÉ OSTŘÍ', 'ЗАТОЧИТЕ СВОЕ ЛЕЗВИЕ', 'BLAĞI BİLEYİN', 'NAOŠTRИТЕ SVOJE OŠTRICE', 'SLIPE DITT BLAD'),
('services_conditioning', 'england_only', 'Please note that this service is only available to players in England.', 'Tenga en cuenta que este servicio solo está disponible para jugadores en Inglaterra.', 'Por favor, note que este serviço está disponível apenas para jogadores na Inglaterra.', 'Veuillez noter que ce service est uniquement disponible pour les joueurs en Angleterre.', 'Bitte beachten Sie, dass dieser Service nur für Spieler in England verfügbar ist.', 'Si prega di notare che questo servizio è disponibile solo per i giocatori in Inghilterra.', 'Proszę pamiętać, że ta usługa jest dostępna tylko dla graczy w Anglii.', 'Upozorňujeme, že tato služba je dostupná pouze pro hráče v Anglii.', 'Обратите внимание, что эта услуга доступна только для игроков в Англии.', 'Lütfen bu hizmetin yalnızca İngiltere''deki oyuncular için mevcut olduğunu unutmayın.', 'Imajte na umu da je ova usluga dostupna samo za igrače u Engleskoj.', 'Vær oppmerksom på at denne tjenesten kun er tilgjengelig for spillere i England.'),

-- NUTRITION PAGE
('services_nutrition', 'category', 'NUTRITION', 'NUTRICIÓN', 'NUTRIÇÃO', 'NUTRITION', 'ERNÄHRUNG', 'NUTRIZIONE', 'ŻYWIENIE', 'VÝŽIVA', 'ПИТАНИЕ', 'BESLENME', 'PREHRANA', 'ERNÆRING'),
('services_nutrition', 'title', 'TO GET THE MOST OUT OF YOURSELF FUELLING PROPERLY IS A MUST', 'PARA SACAR LO MÁXIMO DE TI MISMO, ALIMENTARSE CORRECTAMENTE ES IMPRESCINDIBLE', 'PARA TIRAR O MÁXIMO DE SI MESMO, ABASTECER-SE CORRETAMENTE É ESSENCIAL', 'POUR TIRER LE MEILLEUR DE VOUS-MÊME, SE NOURRIR CORRECTEMENT EST ESSENTIEL', 'UM DAS BESTE AUS SICH HERAUSZUHOLEN, IST RICHTIGE ERNÄHRUNG EIN MUSS', 'PER OTTENERE IL MASSIMO DA SE STESSI, ALIMENTARSI CORRETTAMENTE È UN MUST', 'ABY WYDOBYĆ Z SIEBIE MAKSIMUM, PRAWIDŁOWE ODŻYWIANIE JEST KONIECZNOŚCIĄ', 'ABYSTE ZE SEBE DOSTALI MAXIMUM, SPRÁVNÁ VÝŽIVA JE NUTNOSTÍ', 'ЧТОБЫ ПОЛУЧИТЬ МАКСИМУМ ОТ СЕБЯ, ПРАВИЛЬНОЕ ПИТАНИЕ ОБЯЗАТЕЛЬНО', 'KENDİNİZDEN EN İYİSİNİ ALMAK İÇİN DOĞRU BESLENME ŞARTTIR', 'DA BISTE IZVUKLI NAJBOLJE IZ SEBE, PRAVILNA PREHRANA JE NEOPHODNA', 'FOR Å FÅ DET BESTE UT AV DEG SELV ER RIKTIG ERNÆRING ET MUST'),
('services_nutrition', 'run_further', 'RUN FURTHER', 'CORRE MÁS LEJOS', 'CORRA MAIS', 'COUREZ PLUS LOIN', 'LAUFEN SIE WEITER', 'CORRI PIÙ LONTANO', 'BIEGNIJ DALEJ', 'BĚŽTE DÁLE', 'БЕГИТЕ ДАЛЬШЕ', 'DAHA UZUN KOŞ', 'TRČI DALJE', 'LØP LENGER'),
('services_nutrition', 'run_faster', 'RUN FASTER', 'CORRE MÁS RÁPIDO', 'CORRA MAIS RÁPIDO', 'COUREZ PLUS VITE', 'LAUFEN SIE SCHNELLER', 'CORRI PIÙ VELOCE', 'BIEGNIJ SZYBCIEJ', 'BĚŽTE RYCHLEJI', 'БЕГИТЕ БЫСТРЕЕ', 'DAHA HIZLI KOŞ', 'TRČI BRŽE', 'LØP RASKERE'),
('services_nutrition', 'recover_faster', 'RECOVER FASTER', 'RECUPÉRATE MÁS RÁPIDO', 'RECUPERE-SE MAIS RÁPIDO', 'RÉCUPÉREZ PLUS VITE', 'ERHOLEN SIE SICH SCHNELLER', 'RECUPERA PIÙ VELOCEMENTE', 'REGENERUJ SIĘ SZYBCIEJ', 'ZOTAVTE SE RYCHLEJI', 'ВОССТАНАВЛИВАЙТЕСЬ БЫСТРЕЕ', 'DAHA ÇABUK İYİLEŞ', 'OPORAVI SE BRŽE', 'RESTITUÉR RASKERE'),
('services_nutrition', 'prevent_injuries', 'PREVENT INJURIES', 'PREVENIR LESIONES', 'PREVENIR LESÕES', 'PRÉVENEZ LES BLESSURES', 'VERLETZUNGEN VORBEUGEN', 'PREVIENI GLI INFORTUNI', 'ZAPOBIEGAJ KONTUZJOM', 'PŘEDCHÁZEJTE ZRANĚNÍM', 'ПРЕДОТВРАЩАЙТЕ ТРАВМЫ', 'SAKATLANMALARI ÖNLE', 'SPRIJEČI OZLJEDE', 'FOREBYGG SKADER')
ON CONFLICT DO NOTHING;